# Generated by Django 3.0.6 on 2020-06-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=512)),
                ('Dates', models.CharField(max_length=256)),
                ('Url', models.CharField(max_length=1024)),
            ],
        ),
    ]
