# Generated by Django 3.0.6 on 2020-07-31 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_paper_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
