# Generated by Django 3.0.6 on 2020-08-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_wiki_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wiki_model',
        ),
        migrations.AddField(
            model_name='paper_model',
            name='PaperType',
            field=models.CharField(max_length=64, null='True'),
            preserve_default='True',
        ),
    ]
