# Generated by Django 3.0.6 on 2020-08-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200802_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_model',
            name='Deadline',
            field=models.DateField(max_length=1024, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='paper_model',
            name='Where',
            field=models.CharField(max_length=256, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='paper_model',
            name='Dates',
            field=models.DateField(max_length=256, null='True'),
        ),
    ]
