# Generated by Django 3.0.6 on 2020-08-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200802_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_model',
            name='Dates',
            field=models.CharField(max_length=256, null='True'),
        ),
        migrations.AlterField(
            model_name='paper_model',
            name='Deadline',
            field=models.CharField(max_length=256, null='True'),
        ),
    ]
