# Generated by Django 3.0.6 on 2020-09-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20200802_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_model',
            name='Dates',
            field=models.DateField(max_length=256, null='True'),
        ),
        migrations.AlterField(
            model_name='paper_model',
            name='Deadline',
            field=models.DateField(max_length=256, null='True'),
        ),
        migrations.AlterField(
            model_name='paper_model',
            name='Title',
            field=models.CharField(max_length=1024),
        ),
    ]
