# Generated by Django 3.0.6 on 2020-09-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20200907_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1024)),
                ('Dates', models.CharField(max_length=256, null='True')),
                ('Url', models.CharField(max_length=1024)),
                ('PaperType', models.CharField(max_length=64, null='True')),
                ('Where', models.CharField(max_length=256, null='True')),
                ('Deadline', models.CharField(max_length=256, null='True')),
            ],
        ),
        migrations.AlterField(
            model_name='paper_model',
            name='Dates',
            field=models.CharField(max_length=256, null='True'),
        ),
        migrations.AlterField(
            model_name='paper_model',
            name='Deadline',
            field=models.CharField(max_length=256, null='True'),
        ),
    ]
