# Generated by Django 3.0.6 on 2020-09-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20200907_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_model',
            name='Dates',
            field=models.DateTimeField(null='True'),
        ),
        migrations.AlterField(
            model_name='paper_model',
            name='Deadline',
            field=models.DateTimeField(null='True'),
        ),
    ]
