# Generated by Django 3.0.6 on 2020-09-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20200907_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bmbf_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Proposal', models.CharField(max_length=1024)),
                ('Dates', models.CharField(max_length=256, null='True')),
                ('Url', models.CharField(max_length=1024)),
                ('PaperType', models.CharField(max_length=64, null='True')),
                ('Where', models.CharField(max_length=256, null='True')),
                ('Deadline', models.CharField(max_length=256, null='True')),
            ],
        ),
    ]
