# Generated by Django 3.0.6 on 2020-09-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_bmbf_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmbf_model',
            old_name='Project_Proposal',
            new_name='Title',
        ),
    ]
