# Generated by Django 3.1.7 on 2021-03-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20200914_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1024)),
                ('Dates', models.CharField(max_length=256, null='True')),
                ('Url', models.CharField(max_length=1024)),
                ('PaperType', models.CharField(max_length=64, null='True')),
                ('Where', models.CharField(max_length=256, null='True')),
                ('Deadline', models.CharField(max_length=256, null='True')),
            ],
        ),
    ]
