# Generated by Django 3.0.6 on 2020-09-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20200914_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bmbf_model',
        ),
        migrations.AlterField(
            model_name='paper_model',
            name='Dates',
            field=models.DateTimeField(null='True'),
        ),
    ]
