# Generated by Django 3.0.6 on 2020-09-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20200916_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_model',
            name='Deadline',
            field=models.DateTimeField(null='True'),
        ),
    ]
