# Generated by Django 3.0.6 on 2020-09-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_bmbf_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmbf_model',
            name='Where',
        ),
    ]
