# Generated by Django 3.0.6 on 2020-09-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_remove_bmbf_model_where'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmbf_model',
            name='PaperType',
        ),
    ]
