# Generated by Django 3.0.6 on 2020-09-15 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_remove_bmbf_model_papertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bmbf_model',
        ),
    ]
