# Generated by Django 3.0.6 on 2020-09-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_bmbf_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1024)),
                ('Dates', models.DateTimeField(null='True')),
                ('Url', models.CharField(max_length=1024)),
                ('PaperType', models.CharField(max_length=64, null='True')),
                ('Where', models.CharField(max_length=256, null='True')),
                ('Deadline', models.DateTimeField(null='True')),
            ],
        ),
    ]
