# Generated by Django 3.0.6 on 2020-12-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_wiki_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_model',
            name='Deadline',
        ),
        migrations.AlterModelTable(
            name='wiki_model',
            table='questions_wiki_model',
        ),
    ]
