# Generated by Django 3.0.6 on 2020-12-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_auto_20201207_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper_model',
        ),
    ]
