# Generated by Django 3.0.6 on 2020-05-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='content',
        ),
    ]
