# Generated by Django 3.0.6 on 2020-05-11 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20200510_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='movie1',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
