# Generated by Django 3.0.6 on 2020-05-14 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_todo_movie1'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='movie2',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
