# Generated by Django 3.0.6 on 2020-05-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_todo_movie2'),
    ]

    operations = [
        migrations.CreateModel(
            name='paperscrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventlink', models.CharField(max_length=200)),
                ('eventname', models.CharField(max_length=500)),
                ('dates', models.CharField(max_length=300)),
                ('wheree', models.CharField(max_length=300)),
                ('whene', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='movieinfo',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='movie',
            new_name='dates',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='movie1',
            new_name='whene',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='movie2',
            new_name='wheree',
        ),
    ]
