# Generated by Django 3.0.6 on 2020-05-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20200522_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paperscrapy',
        ),
    ]
