# Generated by Django 3.0.6 on 2020-05-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_delete_paperscrapy'),
    ]

    operations = [
        migrations.CreateModel(
            name='paperscrapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventlink', models.CharField(max_length=200)),
                ('eventname', models.CharField(max_length=500)),
                ('dates', models.CharField(max_length=300)),
                ('wheree', models.CharField(max_length=300)),
                ('whene', models.CharField(max_length=400)),
            ],
        ),
    ]
