# Generated by Django 3.0.6 on 2020-05-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_paperscrapy'),
    ]

    operations = [
        migrations.CreateModel(
            name='paperscrapy1',
            fields=[
                ('eventlink', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=500)),
                ('dates', models.CharField(max_length=300)),
                ('wheree', models.CharField(max_length=300)),
                ('whene', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='paperscrapy',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
