# Generated by Django 3.0.6 on 2020-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_auto_20200524_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='paperscrapying',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventlink', models.CharField(max_length=200)),
                ('eventname', models.CharField(max_length=500)),
                ('dates', models.CharField(max_length=300)),
                ('wheree', models.CharField(max_length=300)),
                ('whene', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='paperscrapy1',
        ),
    ]
